version: '2'

services:
  havoc:
    build: .
    image: havoc
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
    env_file:
      - .env
    depends_on:
      - postgres
    ports: 
      - 666:666
    restart: unless-stopped
 
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    
volumes:
  pgdata:
    driver: local
